version: '3.9'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.8.1-debian-11-r46'
    container_name: zookeeper
    networks:
      kafka-net:
        aliases:
          - zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:3.4.1-debian-11-r4'
    container_name: kafka
    networks:
      kafka-net:
        aliases:
          - kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_BOOTSTRAP_SERVERS=kafka:9091
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_CONTROLLER_LISTENERS=CONTROLLER://kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9091,PLAINTEXT_HOST://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9091,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      kafka-net:
        aliases:
          - mongo
  producer:
    image: visualizer-producer:1.0.0
    container_name: producer
    environment:
      - WEB_SERVER_PORT=29009
      - MONGO_URI=mongodb://mongo:27017/earthquakes
      - KAFKA_BROKER=kafka:9091
      - KAFKA_TOPIC=earthquake
    ports:
      - "29009:29009"
    depends_on:
      - kafka
      - mongo
    networks:
      kafka-net:
        aliases:
          - producer
  consumer:
    image: visualizer-consumer:1.0.0
    container_name: consumer
    environment:
      - KAFKA_BROKER=kafka:9091
      - KAFKA_TOPIC=earthquake
    ports:
      - "3000:3000"
    depends_on:
      - kafka
      - mongo
      - producer
    networks:
      kafka-net:
        aliases:
          - consumer

networks:
  kafka-net:
    driver: bridge
